 server 

 {
     host 127.0.0.1;
     port 3001;
     server_name myserver.com;
     error_page 404 /error_page/404.html;
     client_max_body_size 10m;
     root /public;
	 index form.html 404.html hello.html index.html cgi-form.html;

     location /database/ {
		 autoindex on;
	 }

     location /error_page/ 
     {
         allowed_methods GET POST CIAO;
     }

     location /tests/ {
		return 301 /database/files/;
	 }

 }
 server {
    port 3003;
    host 127.0.0.1;
    server_name yeah.com;
    # error_page 404 /errors/404.html;
    client_max_body_size 10;
    root /public;
    allowed_methods GET POST DELETE
    index index.html index.htm;
}
server {
    port 8081;
    host 127.0.0.;
    server_name yeah.com;
    # error_page 404 /errors/404.html;
    client_max_body_size 10m;
    root /public;
    allowed_methods GET POST DELETE
    index index.html index.htm;
}
server {
    port 4242 3002 3004;
    host 127.0.0.;
    server_name yeah.com;
    error_page 404 /error_page/404.html;
    client_max_body_size 10m;
    root /public;
    allowed_methods GET POST DELETE
    index index.html index.htm index.html;
}


