server {
    port 3001 3005;
    host 127.0.0.1;
    server_name blabla.com wwww.welcome.com welcome.com;
    error_page 404 /error_page/404.html;
    client_max_body_size 100m;
    root /public;
    allowed_methods GET POST DELETE
    index index.html;
}
server {
    port 3003;
    host 127.0.0.;
    server_name yeah.com;
    error_page 404 /errors/404.html;
    client_max_body_size 10000000;
    root /public;
    allowed_methods GET POST DELETE
    index index.html index.htm;
}
